language: rust
cache: cargo
rust:
  - nightly
os: osx
jobs:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - g++-8
            - libpng-dev
            - libglu1-mesa
            - libglu1-mesa-dev
      env:
        - CC=gcc-8
        - CXX=g++-8
    - os: osx
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --examples --verbose
  - cargo doc --no-deps
