language: rust
cache: cargo
rust:
  - nightly
os:
  - linux
  - osx
addons:
  apt:
    packages:
      - xauth
      - xorg
      - openbox
      - mesa-utils
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --no-deps
